PLUGIN_NAME=		notify-greelan
PLUGIN_VERSION=		1.2
PLUGIN_BUNDLED=		apprise
PLUGIN_COMMENT=		Push notifications for system events via Apprise
PLUGIN_MAINTAINER=	Greelan

.include "../../Mk/plugins.mk"
