###################################################################
# Local syslog-ng configuration filter definition [notify].
###################################################################
filter f_local_notify {
    program("notify");
};
