PLUGIN_NAME=		s3-backup-greelan
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Back up the configuration to S3-compatible object storage
PLUGIN_MAINTAINER=	Greelan

.include "../../Mk/plugins.mk"
