PLUGIN_NAME=		blocky-greelan
PLUGIN_VERSION=		1.4
PLUGIN_REVISION=	5
PLUGIN_COMMENT=		Fast and lightweight DNS proxy with ad-blocking
PLUGIN_DEPENDS=		blocky
PLUGIN_CONFLICTS=	blocky
PLUGIN_MAINTAINER=	Greelan

.include "../../Mk/plugins.mk"
