[start]
command:/usr/bin/install -d -m 0750 /var/cache/blocky/lists /var/cache/blocky/hosts /var/db/blocky /var/db/blocky/querylog; /usr/local/opnsense/scripts/OPNsense/Blocky/write_certs.php; /usr/local/etc/rc.d/blocky start
parameters:
type:script
message:starting Blocky

[stop]
command:/usr/local/etc/rc.d/blocky stop
parameters:
type:script
message:stopping Blocky

[restart]
command:/usr/bin/install -d -m 0750 /var/cache/blocky/lists /var/cache/blocky/hosts /var/db/blocky /var/db/blocky/querylog; /usr/local/opnsense/scripts/OPNsense/Blocky/write_certs.php; /usr/local/etc/rc.d/blocky restart
parameters:
type:script
message:restarting Blocky
description:Restart Blocky DNS proxy

[status]
command:/usr/local/etc/rc.d/blocky status; exit 0
parameters:
type:script_output
message:request Blocky status

[import]
command:/usr/local/opnsense/scripts/OPNsense/Blocky/import_config.py
parameters:%s
type:script_output
message:import Blocky configuration

[certificates]
command:/usr/local/opnsense/scripts/OPNsense/Blocky/write_certs.php
parameters:
type:script
message:writing Blocky certificates
