###################################################################
# Local syslog-ng configuration filter definition [blocky].
###################################################################
filter f_local_blocky {
    program("blocky");
};
