[check]
command:/usr/local/bin/flock -n -E 0 -o /var/run/notify.lock /usr/local/opnsense/scripts/OPNsense/Notify/notify.py check
parameters:
type:script
message:checking for notification events

[test]
command:/usr/local/opnsense/scripts/OPNsense/Notify/notify.py test
parameters:%s
type:script_output
message:sending test notification to %s

[summary]
command:/usr/local/bin/flock -w 30 -E 0 -o /var/run/notify.lock /usr/local/opnsense/scripts/OPNsense/Notify/notify.py summary
parameters:%s
type:script_output
message:sending the summary so far to %s

[services]
command:/usr/local/opnsense/scripts/OPNsense/Notify/notify.py services
parameters:
type:script_output
cache_ttl:3600
message:listing Apprise services

[describe]
command:/usr/local/opnsense/scripts/OPNsense/Notify/notify.py describe
parameters:%s
type:script_output
message:describing notification channel %s

[build]
command:/usr/local/opnsense/scripts/OPNsense/Notify/notify.py build
parameters:%s
type:script_output
message:checking notification channel URL

[boot]
command:/usr/local/bin/flock -w 30 -E 0 -o /var/run/notify.lock /usr/local/opnsense/scripts/OPNsense/Notify/notify.py boot
parameters:
type:script
message:sending startup notification

[status]
command:/usr/local/opnsense/scripts/OPNsense/Notify/notify.py status
parameters:
type:script_output
message:reading notification status

[parse]
command:/usr/local/opnsense/scripts/OPNsense/Notify/notify.py parse
parameters:%s
type:script_output
message:reading a pasted notification URL
